services:
  - type: web
    name: location-reminder-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: SESSION_SECRET
        value: your-secret
      - key: DATABASE_URL
        value: your-db-url
      - key: GOOGLE_PLACES_API_KEY
        value: your-google-api-key
